<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountryData extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = array(
            array('name' => 'DEMPO', 'dialcode' => 111),
            array('name' => 'ALGERIA', 'dialcode' => 213),
            array('name' => 'AMERICAN SAMOA', 'dialcode' => 684),
            array('name' => 'ANGUILLA', 'dialcode' => 264),
            array('name' => 'ANTIGUA AND BARBUDA', 'dialcode' => 68),
            array('name' => 'ARGENTINA', 'dialcode' => 54),
            array('name' => 'ARMENIA', 'dialcode' => 374),
            array('name' => 'ARUBA', 'dialcode' => 297),
            array('name' => 'AUSTRIA', 'dialcode' => 43),
            array('name' => 'AZERBAIJAN', 'dialcode' => 994),
            array('name' => 'BAHRAIN', 'dialcode' => 973),
            array('name' => 'BANGLADESH', 'dialcode' => 880),
            array('name' => 'BARBADOS', 'dialcode' => 246),
            array('name' => 'BELARUS', 'dialcode' => 375),
            array('name' => 'BELGIUM', 'dialcode' => 32),
            array('name' => 'BELIZE', 'dialcode' => 501),
            array('name' => 'BENIN', 'dialcode' => 229),
            array('name' => 'BERMUDA', 'dialcode' => 441),
            array('name' => 'BOSNIA AND HERZEGOVINA', 'dialcode' => 387),
            array('name' => 'BOTSWANA', 'dialcode' => 267),
            array('name' => 'BRAZIL', 'dialcode' => 55),
            array('name' => 'BRITISH VIRGIN ISLANDS', 'dialcode' => 284),
            array('name' => 'BRUNEI', 'dialcode' => 673),
            array('name' => 'BULGARIA', 'dialcode' => 359),
            array('name' => 'BURKINA FASO', 'dialcode' => 226),
            array('name' => 'BURMA', 'dialcode' => 95),
            array('name' => 'BURUNDI', 'dialcode' => 257),
            array('name' => 'CAMBODIA', 'dialcode' => 855),
            array('name' => 'CAMEROON', 'dialcode' => 237),
            array('name' => 'CAPE VERDE', 'dialcode' => 238),
            array('name' => 'CAYMAN ISLANDS', 'dialcode' => 345),
            array('name' => 'CENTRAL AFRICAN REPUBLIC', 'dialcode' => 236),
            array('name' => 'CHAD', 'dialcode' => 235),
            array('name' => 'CHILE', 'dialcode' => 56),
            array('name' => 'CHINA', 'dialcode' => 86),
            array('name' => 'COLOMBIA', 'dialcode' => 57),
            array('name' => 'COMOROS', 'dialcode' => 269),
            array('name' => 'CONGO (KINSHASA)', 'dialcode' => 243),
            array('name' => 'CONGO (BRAZZAVILLE)', 'dialcode' => 242),
            array('name' => 'COOK ISLANDS', 'dialcode' => 682),
            array('name' => 'COSTA RICA', 'dialcode' => 506),
            array('name' => 'CROATIA', 'dialcode' => 385),
            array('name' => 'CUBA', 'dialcode' => 53),
            array('name' => 'CYPRUS', 'dialcode' => 357),
            array('name' => 'CZECH REPUBLIC', 'dialcode' => 420),
            array('name' => 'DENMARK', 'dialcode' => 45),
            array('name' => 'DJIBOUTI','dialcode' => 253),
            array('name' => 'DOMINICA','dialcode' => 767),
            array('name' => 'BAHAMAS THE','dialcode' => 242),
            array('name' => 'ANDORRA', 'dialcode' => 376),
            array('name' => 'CANADA', 'dialcode' => 1),
            array('name' => 'COTE D IVOIRE', 'dialcode' => 225),
            array('name' => 'ANGOLA', 'dialcode' => 244),
            array('name' => 'ALBANIA','shortname' => 'DFS', 'dialcode' => 355),
            array('name' => 'BOLIVIA', 'dialcode' => 591),
            array('name' => 'BHUTAN', 'dialcode' => 975),
            array('name' => 'AUSTRALIA', 'dialcode' => 61),
            array('name' => 'DOMINICAN REPUBLIC', 'dialcode' => 809),
            array('name' => 'TIMOR-LESTE', 'dialcode' => 670),
            array('name' => 'ECUADOR', 'dialcode' => 593),
            array('name' => 'EGYPT', 'dialcode' => 20),
            array('name' => 'EL SALVADOR', 'dialcode' => 503),
            array('name' => 'EQUATORIAL GUINEA', 'dialcode' => 240),
            array('name' => 'ERITREA', 'dialcode' => 291),
            array('name' => 'ESTONIA', 'dialcode' => 372),
            array('name' => 'ETHIOPIA', 'dialcode'=> 251),
            array('name' => 'FAROE ISLANDS', 'dialcode'=> 298),
            array('name' => 'FIJI', 'dialcode'=> 679),
            array('name' => 'FINLAND', 'dialcode'=> 358),
            array('name' => 'FRANCE', 'dialcode'=> 33),
            array('name' => 'FRENCH GUIANA', 'dialcode'=> 594),
            array('name' => 'FRENCH POLYNESIA', 'dialcode'=> 689),
            array('name' => 'GABON', 'dialcode'=> 241),
            array('name' => 'GAMBIA', 'dialcode'=> 220),
            array('name' => 'GAZA STRIP', 'dialcode'=> 970),
            array('name' => 'GEORGIA', 'dialcode'=> 995),
            array('name' => 'GERMANY', 'dialcode'=> 49),
            array('name' => 'GHANA', 'dialcode'=> 233),
            array('name' => 'GIBRALTAR', 'dialcode'=> 350),
            array('name' => 'GREECE', 'dialcode'=> 30),
            array('name' => 'GREENLAND', 'dialcode'=> 299),
            array('name' => 'GRENADA', 'dialcode'=> 473),
            array('name' => 'GUADELOUPE', 'dialcode'=> 590),
            array('name'=> 'GUAM', 'dialcode' => 671),
            array('name'=> 'GUATEMALA', 'dialcode' => 502),
            array('name'=> 'GUERNSEY', 'dialcode' => 44),
            array('name'=> 'GUINEA', 'dialcode' => 224),
            array('name'=> 'GUINEA-BISSAU', 'dialcode' => 245),
            array('name'=> 'GUYANA', 'dialcode' => 592),
            array('name'=> 'HAITI', 'dialcode' => 509),
            array('name'=> 'HONDURAS', 'dialcode' => 504),
            array('name'=> 'HONG KONG', 'dialcode' => 852),
            array('name'=> 'HUNGARY', 'dialcode' => 36),
            array('name'=> 'ICELAND', 'dialcode' => 354),
            array('name'=> 'INDIA', 'dialcode' => 91),
            array('name'=> 'INDONESIA', 'dialcode' => 62),
            array('name'=> 'IRAN', 'dialcode' => 98),
            array('name'=> 'IRAQ', 'dialcode' => 964),
            array('name'=> 'IRELAND', 'dialcode' => 353),
            array('name'=> 'ISLE OF MAN', 'dialcode' => 44),
            array('name' => 'ISRAEL', 'dialcode' => 972),
            array('name' => 'ITALY', 'dialcode' => 39),
            array('name' => 'JAMAICA', 'dialcode' => 876),
            array('name' => 'JAPAN', 'dialcode' => 81),
            array('name' => 'JERSEY', 'dialcode' => 44),
            array('name' => 'JORDAN', 'dialcode' => 962),
            array('name' => 'KAZAKHSTAN', 'dialcode' => 7),
            array('name' => 'KENYA', 'dialcode' => 254),
            array('name' => 'KIRIBATI', 'dialcode' => 686),
            array('name' => 'NORTH KOREA', 'dialcode' => 850),
            array('name' => 'SOUTH KOREA', 'dialcode' => 82),
            array('name' => 'KUWAIT', 'dialcode' => 965),
            array('name' => 'KYRGYZSTAN', 'dialcode' => 996),
            array('name' => 'LAOS', 'dialcode' => 856),
            array('name' => 'LATVIA', 'dialcode' => 371),
            array('name' => 'LEBANON', 'dialcode' => 961),
            array('name' => 'LESOTHO', 'dialcode' => 266),
            array('name' => 'LIBERIA', 'dialcode' => 231),
            array('name' => 'LIBYA', 'dialcode' => 218),
            array('name' => 'LIECHTENSTEIN', 'dialcode' => 423),
            array('name' => 'LITHUANIA', 'dialcode' => 370),
            array('name' => 'LUXEMBOURG', 'dialcode' => 352),
            array('name' => 'MACAU', 'dialcode' => 853),
            array('name' => 'MACEDONIA', 'dialcode' => 389),
            array('name' => 'MADAGASCAR', 'dialcode' => 261),
            array('name' => 'MALAWI', 'dialcode' => 265),
            array('name' => 'MALAYSIA', 'dialcode' => 60),
            array('name' => 'MALDIVES', 'dialcode' => 960),
            array('name' => 'MALI', 'dialcode' => 223),
            array('name' => 'MALTA', 'dialcode' => 356),
            array('name' => 'MARSHALL ISLANDS', 'dialcode' => 692),
            array('name' => 'MARTINIQUE', 'dialcode' => 596),
            array('name' => 'MAURITANIA', 'dialcode' => 222),
            array('name' => 'MAURITIUS', 'dialcode' => 230),
            array('name' => 'MAYOTTE', 'dialcode' => 269),
            array('name' => 'MEXICO', 'dialcode' => 52),
            array('name' => 'MICRONESIA', 'dialcode' => 691),
            array('name' => 'MOLDOVA', 'dialcode' => 373),
            array('name' => 'MONACO', 'dialcode' => 377),
            array('name' => 'MONGOLIA', 'dialcode' => 976),
            array('name' => 'MONTSERRAT', 'dialcode' => 664),
            array('name' => 'MOROCCO', 'dialcode' => 212),
            array('name' => 'MOZAMBIQUE', 'dialcode' => 258),
            array('name' => 'NAMIBIA', 'dialcode' => 264),
            array('name' => 'NAURU', 'dialcode' => 674),
            array('name' => 'NEPAL', 'dialcode' => 977),
            array('name' => 'NETHERLANDS', 'dialcode' => 31),
            array('name' => 'NETHERLANDS ANTILLES', 'dialcode' => 599),
            array('name' => 'NEW CALEDONIA', 'dialcode' => 687),
            array('name' => 'NEW ZEALAND', 'dialcode' => 64),
            array('name' => 'NICARAGUA', 'dialcode' => 505),
            array('name' => 'NIGER', 'dialcode' => 227),
            array('name' => 'NIGERIA', 'dialcode' => 234),
            array('name' => 'NORTHERN MARIANA ISLANDS', 'dialcode' => 670),
            array('name' => 'NORWAY', 'dialcode' => 47),
            array('name' => 'OMAN', 'dialcode' => 968),
            array('name' => 'PAKISTAN', 'dialcode' => 92),
            array('name' => 'PALAU', 'dialcode' => 680),
            array('name' => 'PANAMA', 'dialcode' => 507),
            array('name' => 'PAPUA NEW GUINEA', 'dialcode' => 675),
            array('name' => 'PARAGUAY', 'dialcode' => 595),
            array('name' => 'PERU', 'dialcode' => 51),
            array('name' => 'PHILIPPINES', 'dialcode' => 63),
            array('name' => 'POLAND', 'dialcode' => 48),
            array('name' => 'PORTUGAL', 'dialcode' => 351),
            array('name' => 'PUERTO RICO', 'dialcode' => 787),
            array('name' => 'QATAR', 'dialcode' => 974),
            array('name' => 'REUNION', 'dialcode' => 262),
            array('name' => 'ROMANIA', 'dialcode' => 40),
            array('name' => 'RUSSIA', 'dialcode' => 7),
            array('name' => 'RWANDA', 'dialcode' => 250),
            array('name' => 'SAINT HELENA', 'dialcode' => 290),
            array('name' => 'SAINT KITTS AND NEVIS', 'dialcode' => 869),
            array('name' => 'SAINT LUCIA', 'dialcode' => 758),
            array('name' => 'ST PIERRE AND MIQUELON', 'dialcode' => 508),
            array('name' => 'SAINT VINCENT AND THE GRENADINES', 'dialcode' => 784),
            array('name' => 'SAMOA', 'dialcode' => 685),
            array('name' => 'SAN MARINO', 'dialcode' => 378),
            array('name' => 'SAO TOME AND PRINCIPE', 'dialcode' => 239),
            array('name' => 'SAUDI ARABIA', 'dialcode' => 966),
            array('name' => 'SENEGAL', 'dialcode' => 221),
            array('name' => 'SERBIA', 'dialcode' => 381),
            array('name' => 'SEYCHELLES', 'dialcode' => 248),
            array('name' => 'SIERRA LEONE', 'dialcode' => 232),
            array('name' => 'SINGAPORE', 'dialcode' => 65),
            array('name' => 'SLOVAKIA', 'dialcode' => 421),
            array('name' => 'SLOVENIA', 'dialcode' => 386),
            array('name' => 'SOLOMON ISLANDS', 'dialcode' => 677),
            array('name' => 'SOMALIA', 'dialcode' => 252),
            array('name' => 'SOUTH AFRICA', 'dialcode' => 27),
            array('name' => 'SPAIN', 'dialcode' => 34),
            array('name' => 'SRI LANKA', 'dialcode' => 94),
            array('name' => 'SUDAN', 'dialcode' => 249),
            array('name' => 'SURINAME', 'dialcode' => 597),
            array('name' => 'SWAZILAND', 'dialcode' => 268),
            array('name' => 'SWEDEN', 'dialcode' => 46),
            array('name' => 'SWITZERLAND', 'dialcode' => 41),
            array('name' => 'SYRIA', 'dialcode' => 963),
            array('name' => 'TAIWAN', 'dialcode' => 886),
            array('name' => 'TAJIKISTAN', 'dialcode' => 992),
            array('name' => 'TANZANIA', 'dialcode' => 255),
            array('name' => 'THAILAND', 'dialcode' => 66),
            array('name' => 'TOGO', 'dialcode' => 228),
            array('name' => 'TONGA', 'dialcode' => 676),
            array('name' => 'TRINIDAD AND TOBAGO', 'dialcode' => 868),
            array('name' => 'TUNISIA', 'dialcode' => 216),
            array('name' => 'TURKEY', 'dialcode' => 90),
            array('name' => 'TURKMENISTAN', 'dialcode' => 993),
            array('name' => 'TURKS AND CAICOS IS', 'dialcode' => 649),
            array('name' => 'TUVALU', 'dialcode' => 688),
            array('name' => 'UGANDA', 'dialcode' => 256),
            array('name' => 'UKRAINE', 'dialcode' => 380),
            array('name' => 'UNITED ARAB EMIRATES', 'dialcode' => 971),
            array('name' => 'UNITED KINGDOM', 'dialcode' => 44),
            array('name' => 'UNITED STATES', 'dialcode' => 1),
            array('name' => 'URUGUAY', 'dialcode' => 598),
            array('name' => 'UZBEKISTAN', 'dialcode' => 998),
            array('name' => 'VANUATU', 'dialcode' => 678),
            array('name' => 'VENEZUELA', 'dialcode' => 58),
            array('name' => 'VIETNAM', 'dialcode' => 84),
            array('name' => 'WALLIS AND FUTUNA', 'dialcode' => 681),
            array('name' => 'WEST BANK', 'dialcode' => 970),
            array('name' => 'WESTERN SAHARA', 'dialcode' => 212),
            array('name' => 'YEMEN', 'dialcode' => 967),
            array('name' => 'ZAMBIA', 'dialcode' => 260),
            array('name' => 'ZIMBABWE', 'dialcode' => 263),
            array('name' => 'MONTEGRO', 'dialcode' => 382),
            array('name' => 'NIUE', 'dialcode' => 683),
            array('name' => 'FALKLAND ISLANDS', 'dialcode' => 500),
            array('name' => 'NORFOLK ISLAND', 'dialcode' => 672),
            array('name' => 'PITCAIRN', 'dialcode' => 64),
            array('name' => 'SAINT BARTHELEMY', 'dialcode' => 50),
            array('name' => 'SVALBARD', 'dialcode' => 47),
            array('name' => 'AFGHANISTAN', 'dialcode' => 93),
        );

        foreach($countries as $country){
            Country::create([
                'name' => $country['name'],
                'dialcode' => $country['dialcode']
            ]);
        }
    }
}
